### ISSUE TITLE
Data format for domain trusts

### ISSUE THREAD

**Issue by scaise** [fox-it/BloodHound.py#107]
Hello,

Just wondered if I could get some clarification from somebody more in the know than myself. I've recently been working with Domain Trusts and have a similar issue to: https://github.com/fox-it/BloodHound.py/issues/84#issue-1159460746

When looking for domain trusts in Bloodhound, I was not seeing anything. I know they exist as I've enumerated trusts using another tool but when loading Sharphound data into Bloodhound the trusts are not displayed.

I came across the issue linked above whereby Bloodhound.py was using int values to identify trust directions and types. This was confirmed as a bug and fixed.

I appear to be having the same issues with Sharphound. The data is displayed as an integer, when bloodhound is looking for a string, see below:

`                {
                    "TargetDomainSid": "redacted",
                    "TargetDomainName": "redacted",
                    "IsTransitive": true,
                    "SidFilteringEnabled": false,
                    "TrustDirection": 1,
                    "TrustType": 4
                }`

When the above is loaded into Bloodhound, the trusts are not displayed. If I manually modify this with the correct string as shown below, Bloodhound displays the trust:

`
                {
                    "TargetDomainSid": "redacted",
                    "TargetDomainName": "redacted",
                    "IsTransitive": true,
                    "SidFilteringEnabled": false,
                    "TrustDirection": "Inbound",
                    "TrustType": "Forest"
                }
`

Is this also a bug in Sharphound, or is there something I'm missing here?

**Comment by dirkjanm** [comment]
Are you sure you have the latest version of SharpHound and BloodHound? In any case, this repository is for the python data collector, while your bug appears to relate to SharpHound, and not to bloodhound python. If you still have this issue after upgrading to the latest version I suggest opening an issue there https://github.com/BloodHoundAD/SharpHound
