### ISSUE TITLE
LDAPNoSuchObjectResult Exception

### ISSUE THREAD

**Issue by dreadsystems** [fox-it/BloodHound.py#11]
Ran this tool with the following format:

root@box:/opt/BloodHound.py# bloodhound-python -u user -p pass -d domain -ns 192.168.1.100

After the recent update, this crash results:

INFO: Found AD domain: somedomain.com
INFO: Connecting to LDAP server: somedc.somedomain.com
INFO: Found 1 domains
INFO: Found 1 domains in the forest
INFO: Found 1384 computers
INFO: Found 973 groups
WARNING: Warning: Unknown primarygroupid 512
INFO: Connecting to GC LDAP server: somedc.somedomain.com
Traceback (most recent call last):
  File "/usr/local/bin/bloodhound-python", line 11, in <module>
    load_entry_point('bloodhound==0.4.0', 'console_scripts', 'bloodhound-python')()
  File "build/bdist.linux-x86_64/egg/bloodhound/__init__.py", line 194, in main
  File "build/bdist.linux-x86_64/egg/bloodhound/__init__.py", line 68, in run
  File "build/bdist.linux-x86_64/egg/bloodhound/enumeration/memberships.py", line 96, in enumerate_memberships
  File "build/bdist.linux-x86_64/egg/bloodhound/enumeration/memberships.py", line 54, in write_membership
  File "build/bdist.linux-x86_64/egg/bloodhound/enumeration/objectresolver.py", line 51, in resolve_group
  File "build/bdist.linux-x86_64/egg/bloodhound/ad/domain.py", line 124, in ldap_get_single
  File "/usr/local/lib/python2.7/dist-packages/ldap3/extend/__init__.py", line 125, in paged_search
    paged_criticality)
  File "/usr/local/lib/python2.7/dist-packages/ldap3/extend/standard/PagedSearch.py", line 121, in paged_search_accumulator
    paged_criticality):
  File "/usr/local/lib/python2.7/dist-packages/ldap3/extend/standard/PagedSearch.py", line 84, in paged_search_generator
    raise LDAPOperationResult(result=result['result'], description=result['description'], dn=result['dn'], message=result['message'], response_type=result['type'])
ldap3.core.exceptions.LDAPNoSuchObjectResult: LDAPNoSuchObjectResult - 32 - noSuchObject - OU=Enterprise Admins,DC=somedomain,DC=com - 0000208D: NameErr: DSID-0315270B, problem 2001 (NO_OBJECT), data 0, best match of:
        'OU=Enterprise Admins,DC=somedomain,DC=com'
 - searchResDone - None

Running v0.3.2 (May release) of this tool works fine.

**Comment by dirkjanm** [comment]
That is interesting. Is there in fact only one domain in the forest or is this also incorrect? The May release doesn't consider other domains in the forest yet so it makes sense that this error wouldn't pop up there.

**Comment by dreadsystems** [comment]
There appears to be only one domain in the forest, but I am not completely certain yet. I'll be more sure after working my way around the network for a bit. 

I can double check against the Windows version as well once I get a couple of Windows shells.

**Comment by dirkjanm** [comment]
That would be great! Some better error handling wouldn't hurt here but I'm curious as why it doesn't see the group with ID 512 (domain admins) and why the tool feels the need to query the global catelog in a single domain environment.

**Comment by dreadsystems** [comment]
After obtaining domain admin (equivalent) privs, I played around the network for a bit. They actually don't have any domain admins that are readable/queryable, there's an access control feature in AD that could be set up to prevent reading contents of that group. The Windows BloodHound collector (SharpHound.ps1) was a bit more thorough just because of the extra CSV's it generates like user_props, computer_props, etc... but regardless, I'm wondering if having no visible DA's was giving this tool some issues.

**Comment by dirkjanm** [comment]
Thank you for the extensive feedback! This is quite interesting as I haven't encountered such a setup before. Maybe they deny reading the domain admin group members to users. I'll take this into consideration and add some fixes to the error handling which should at least make sure the tool doesn't crash in these cases.

**Comment by dreadsystems** [comment]
My pleasure, and thanks for your time developing this tool.

**Comment by dirkjanm** [comment]
This should be handled better now. If you're still in a position to re-run bloodhound, let me know if it indeed does or if it breaks somewhere else.

**Comment by dreadsystems** [comment]
Tested this again, all is well.

**Comment by dirkjanm** [comment]
Great, thanks for the feedback :)
