### ISSUE TITLE
Feature Request - Exclude DC

### ISSUE THREAD

**Issue by zflemingg1** [fox-it/BloodHound.py#111]
Ability to exclude DC's to avoid some detections, same as Sharphound

**Comment by amirr0r** [comment]
In the meantime, you can append the list of DC hostnames in `bloodhound/enumeration/computers.py` ✌️ :

```py
56         # blocklist and allowlist are only used for debugging purposes
57         self.blocklist = ['dc.example.lab']
```

**Comment by dirkjanm** [comment]
I've added this in the latest version
