### ISSUE TITLE
Username compare failing when usernames match but are not same case

### ISSUE THREAD

**Issue by amspartacus1** [fox-it/BloodHound.py#114]
https://github.com/fox-it/BloodHound.py/blob/dea250078b3728cc3bcbe60033138b39c0d34f93/bloodhound/ad/authentication.py#L283

The username comparison `if expected_principal != str(tgt_principal):` fails when supplied username and ccache username are the same user but not the same case (e.g. USER1 != user1). It looks like tgt_principal may need to be lower-cased so will succeed when compared to the expected_principal which is lowercase if the usernames are effectively the same.

**Comment by dirkjanm** [comment]
thanks for the report, should be fixed in latest commit on master
