### ISSUE TITLE
Bump to a new minor version

### ISSUE THREAD

**Issue by mpgn** [fox-it/BloodHound.py#124]
Hello @dirkjanm 

This commit resolve a big problem when using bloodhound.py as a lib but it is not available on pypi. Can you push a minor version ? :)

https://github.com/fox-it/BloodHound.py/commit/b81f83f6564d3c73e6326a552575cc74ff76bbb3

Thanks, regards :)

**Comment by dirkjanm** [comment]
Thanks for the reminder, just pushed v1.6.1. Also, great work on including bloodhound.py in CME <3
