### ISSUE TITLE
Won't work with bloodhound 4.2

### ISSUE THREAD

**Issue by CaledoniaProject** [fox-it/BloodHound.py#130]
I got this weird error while uploading the generated json file:

![qwe](https://user-images.githubusercontent.com/1357701/232316592-2c0b3c28-b3ae-4ce2-ad9c-c655c0ad72df.jpg)

**Comment by dirkjanm** [comment]
Sounds like you're working with an outdated version. I recommend running this from a virtualenv to make sure you have the latest release which works with bloodhound 4.2
