### ISSUE TITLE
Return JSON results through function call 

### ISSUE THREAD

**Issue by bm1391** [fox-it/BloodHound.py#21]
First, thanks for the tool!

Second, is there a easy place in the code to return a JSON object instead of having it write out to a file? Basically, I would like to call the bloodhound collector from my own code and get a JSON object. Something like this

> def mytest():
>     results = bloodhound(params)
>     print results # JSON result here

Looks like the file is being created in `outputworker.py` and a couple others so I figured I can create JSON objects there, redirect it to a function and return the result?

I believe I can accomplish this but if you had any tips while I look over the code that would be great!

Thanks

**Comment by bm1391** [comment]
At second glance this might be tougher than I thought with the daemon queues...

**Comment by dirkjanm** [comment]
This is not really possible. BloodHound enumerates in phases and outputs different json files at the end of each phase. The best approach is to run bloodhound and then read the files from disk.

**Comment by bm1391** [comment]
Yeah.... I just went with adding the JSON outputs to a database when the Queues complete and grabbing it from there. Thanks for the quick answer.
