### ISSUE TITLE
DNS Timeout Issue

### ISSUE THREAD

**Issue by aconite33** [fox-it/BloodHound.py#29]
First off, you guys are awesome and I love using this. This has helped me out alot when I get funky issues with SharpHound.

Recently on an OP I was completely remote and didn't have a system on site, but didn't have the ability to run SharpHound. I was using socks proxy to conduct my 3rd party toolset. Enter BloodHound.py.

I was able to get everything setup, but notice I wasn't getting dns resolution. After RTFM, I see that I can flip --dcp-tcp, which worked great, but kept getting a time out issue. I ended up modifying the domain.py and setting the timeout to 30 seconds, which allowed enough time for the resolve to happen and get back an answer.

Would it be possible to add a switch to the DNS timeout, in case I need to do this from the command line?

**Comment by mubix** [comment]
I have used DNSChef - https://github.com/iphelix/dnschef to fake the DNS requests to get around the time out issue. It supports SRV and A records and that's really all that is needed.

**Comment by BroadbentT** [comment]
Just ran into this issue - fix on way ?

**Comment by dirkjanm** [comment]
this is now supported with the `--dns-timeout` parameter.

**Comment by AlanFoster** [comment]
I was hitting timeout issues as well as other DNS issues when running through proxychains when I found this issue

> I have used DNSChef - https://github.com/iphelix/dnschef to fake the DNS requests to get around the time out issue. 

I was able to use DNSChef to get a succesful bloodhound.py dump through proxychains - for any future travelelrs mubix has a video about that here https://www.youtube.com/watch?v=4ydjpSSKQ8g
