### ISSUE TITLE
Python 3.8 compatibility

### ISSUE THREAD

**Issue by argb10** [fox-it/BloodHound.py#46]
Hello ^^ 
I recently 'pip3 install bloodhound' and cloned, in Python 3.8, and I got this error message: 'TypeError: Missing required parameter 'digestmod'.'

Googling it I found this:
[https://github.com/SecureAuthCorp/impacket/pull/711#issue-346729192](url)

Maybe you need to add 'digestmod=hashlib.md5'?

Thank you in advanced for your time. :)

> Complete error message:
> Traceback (most recent call last):
>   File "bloodhound.py", line 5, in <module>
>     bloodhound.main()
>   File "/home/kali/HacktheBoox/Pathfinder/bloodhound/bloodhound/__init__.py", line 284, in main
>     bloodhound.run(collect=collect,
>   File "/home/kali/HacktheBoox/Pathfinder/bloodhound/bloodhound/__init__.py", line 72, in run
>     self.pdc.prefetch_info('objectprops' in collect, 'acl' in collect)
>   File "/home/kali/HacktheBoox/Pathfinder/bloodhound/bloodhound/ad/domain.py", line 394, in prefetch_info
>     self.get_objecttype()
>   File "/home/kali/HacktheBoox/Pathfinder/bloodhound/bloodhound/ad/domain.py", line 224, in get_objecttype
>     self.ldap_connect()
>   File "/home/kali/HacktheBoox/Pathfinder/bloodhound/bloodhound/ad/domain.py", line 68, in ldap_connect
>     ldap = self.ad.auth.getLDAPConnection(hostname=ip,
>   File "/home/kali/HacktheBoox/Pathfinder/bloodhound/bloodhound/ad/authentication.py", line 78, in getLDAPConnection
>     if not conn.bind():
>   File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 563, in bind
>     response = self.do_ntlm_bind(controls)
>   File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 1302, in do_ntlm_bind
>     request = bind_operation(self.version, 'SICILY_RESPONSE_NTLM', ntlm_client, result['server_creds'])
>   File "/usr/lib/python3/dist-packages/ldap3/operation/bind.py", line 81, in bind_operation
>     server_creds = name.create_authenticate_message()
>   File "/usr/lib/python3/dist-packages/ldap3/utils/ntlm.py", line 379, in create_authenticate_message
>     nt_challenge_response = self.compute_nt_response()
>   File "/usr/lib/python3/dist-packages/ldap3/utils/ntlm.py", line 485, in compute_nt_response
>     response_key_nt = self.ntowf_v2()
>   File "/usr/lib/python3/dist-packages/ldap3/utils/ntlm.py", line 497, in ntowf_v2
>     return hmac.new(password_digest, (self.user_name.upper() + self.user_domain).encode('utf-16-le')).digest()
>   File "/usr/lib/python3.8/hmac.py", line 153, in new
>     return HMAC(key, msg, digestmod)
>   File "/usr/lib/python3.8/hmac.py", line 51, in __init__
>     raise TypeError("Missing required parameter 'digestmod'.")
> TypeError: Missing required parameter 'digestmod'.

**Comment by dirkjanm** [comment]
This is an issue with `ldap3`, which according to their [source code](https://github.com/cannatag/ldap3/blame/afa62995290cdcbde2019ecd26f5c961a8b4492d/ldap3/utils/ntlm.py#L486) was already fixed a while back. Could you make sure to uninstall any version of ldap3 bundled with Kali and install the latest version using pip?

**Comment by argb10** [comment]
Couldn't uninstall via pip3 so I had to:
```
sudo rm -rf /usr/lib/python3/dist-packages/ldap3*
sudo pip3 install ldap3
```
Looks like, did the trick, but now I got another error message:
 ```
cannot import name 'PyAsn1UnicodeDecodeError' from 'pyasn1.error'
```
So I trigger the nuke of upgrades :)
```
sudo apt update -y && sudo apt dist-upgrade -y && sudo apt autoremove --> up to date
python3 -m pip install --upgrade pip --> up to date
```
Pyasn upgrade:
```
sudo pip3 uninstall pyasn
sudo pip3 install pyasn
sudo pip3 install --upgrade pyasn
```
Installed the same version :(
```
Requirement already up-to-date: pyasn in /usr/local/lib/python3.8/dist-packages (1.6.0b1)
```
Finally eager upgrade-strategy  did the trick:
```
sudo pip3 install -U ldap3 --upgrade-strategy eager
```
Thank you for your time :100:

**Comment by vs45sharma** [comment]
> Couldn't uninstall via pip3 so I had to:
> 
> ```
> sudo rm -rf /usr/lib/python3/dist-packages/ldap3*
> sudo pip3 install ldap3
> ```
> 
> Looks like, did the trick, but now I got another error message:
> 
> ```
> cannot import name 'PyAsn1UnicodeDecodeError' from 'pyasn1.error'
> ```
> 
> So I trigger the nuke of upgrades :)
> 
> ```
> sudo apt update -y && sudo apt dist-upgrade -y && sudo apt autoremove --> up to date
> python3 -m pip install --upgrade pip --> up to date
> ```
> 
> Pyasn upgrade:
> 
> ```
> sudo pip3 uninstall pyasn
> sudo pip3 install pyasn
> sudo pip3 install --upgrade pyasn
> ```
> 
> Installed the same version :(
> 
> ```
> Requirement already up-to-date: pyasn in /usr/local/lib/python3.8/dist-packages (1.6.0b1)
> ```
> 
> Finally eager upgrade-strategy did the trick:
> 
> ```
> sudo pip3 install -U ldap3 --upgrade-strategy eager
> ```
> 
> Thank you for your time 💯

That's Work Thank Buddy 👍
