### ISSUE TITLE
membership_write_worker - corrupt data during an exception

### ISSUE THREAD

**Issue by TheNoButton** [fox-it/BloodHound.py#57]
I found out today that https://github.com/fox-it/BloodHound.py/blob/fd793b94d6e3a4238c5451ab76915bce59ae5ed0/bloodhound/enumeration/outputworker.py#L59  will write part of the user object to `membership_out` before throwing a `TypeError`.  The partial object corrupts the whole JSON file.

Better to buffer to a string first before writing to the file?
```
--- a/bloodhound/enumeration/outputworker.py
+++ b/bloodhound/enumeration/outputworker.py
@@ -103,7 +103,8 @@ class OutputWorker(object):
             if num_members != 0:
                 membership_out.write(',')
             try:
-                json.dump(data, membership_out, indent=indent_level)
+                encoded_member = json.dumps(data, indent=indent_level)
+                membership_out.write(encoded_member)
             except TypeError:
                 logging.error('Data error {0}, could not convert data to json'.format(repr(data)))
                 membership_out.write('{}')
```

It looks like that pattern is used a few times in `outputworker.py`

**Comment by dirkjanm** [comment]
I agree this would be a slight improvement, however this still leaves incomplete results because of non-convertible data. I'd prefer to fix the data that can't be converted than introduce workarounds. Any chance you have an example of the typeerror that was thrown?

**Comment by TheNoButton** [comment]
Much to my surprise, I still have the exception log from the docker container.  The value for the `userPassword` attribute was a binary string, which is what `json.dump()` choked on, shown below.  (BTW, we were all surprised to see a readable `userPassword` attribute.  We had exactly one user with that in the directory.)

Here is the (redacted) data that was written to the file, including the trailing `{}` from the exception handler.  You can see it dies right after writing the `userpassword` key.  Once I removed all of this text, bloodhoud was able to import the remaining valid JSON.  (Though, removing it was non-trivial as my users.json was just shy of 1GB and this was right in the middle of it).
```
{"AllowedToDelegate": [], "ObjectIdentifier": "S-1-5-21-555555555-5555555555-5555555555-263586", "PrimaryGroupSid": "S-1-5-21-555555555-5555555555-5555555555-513", "Properties": {"name": "redacted7@EXAMPLE.EDU", "domain": "EXAMPLE.EDU", "objectid": "S-1-5-21-555555555-5555555555-5555555555-263586", "distinguishedname": "CN=redacted7,OU=Sponsored Users,DC=example,DC=edu", "highvalue": false, "unconstraineddelegation": false, "passwordnotreqd": false, "enabled": true, "lastlogon": -1, "lastlogontimestamp": 1464730667, "pwdlastset": 1464753766, "dontreqpreauth": false, "pwdneverexpires": true, "sensitive": false, "serviceprincipalnames": [], "hasspn": false, "displayname": null, "email": null, "title": null, "homedirectory": null, "description": null, "userpassword": {},
```

And, an example of json choking on binary strings

```
In [1]: import json

In [2]: foo = {'userpassword': b'password'}

In [3]: json.dumps(foo)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[ ... traceback here ... ]

TypeError: Object of type bytes is not JSON serializable
```
I suppose this https://github.com/fox-it/BloodHound.py/blob/fd793b94d6e3a4238c5451ab76915bce59ae5ed0/bloodhound/ad/utils.py#L256 needs something like a `if type(...) is bytes:`

Even if that gets a patch, I still think it's a good idea to try to catch any other future encoding exceptions before they are written to the file to avoid these partial objects from being written.

**Comment by dirkjanm** [comment]
thanks for the additional info, I've added your proposed caching of the json output, and have also added some code that ensures the userpassword attribute is always a string. hope this solves it since I have no way of testing this right now

**Comment by TheNoButton** [comment]
Thanks!  I actually was working on making a pull request for this last week but got burned by #61 and set it aside.  I'm glad both got patched up.

**Comment by shaaati** [comment]
I stumbled upon this issue because I was using an outdated version of bloodhound-python.
Just as @TheNoButton, I had two(?) user accounts in the Active Directory which had a readable `userpassword` value, encoded as a binary string.
While your fix from https://github.com/fox-it/BloodHound.py/commit/c2e8bd9f364f0ea9bd1c2000f052b2b5bd987890 seemed to help, I don't like the fact that we are losing the accounts in question from bloodhound this way.

Maybe a conversion from binary string could be added to the software, as it seems that we now have at least two individual occurences of this behavior?
