### ISSUE TITLE
Rust and Cryptography module

### ISSUE THREAD

**Issue by circleous** [fox-it/BloodHound.py#61]
As mentioned [here](https://github.com/pyca/cryptography/issues/5771#issuecomment-775990406), many-musl release build on PyPI wheel to support alpine is still on the way. In the meanwhile should I disable Rust build? This breaks on the current docker build.

**Comment by ejohn** [comment]
@circleous  if you are looking for a workaround to build the container, add rust and cargo as dependencies to the dockerfile. I have a [PR submitted](https://github.com/fox-it/BloodHound.py/pull/62/files).

**Comment by circleous** [comment]
This is probably just a rant, but I still didn't know what's the actual reason for the cryptography package maintainer to use rust. AFAICS, currently the rust part of the package is just [padding related functions](https://github.com/pyca/cryptography/blob/82a12a54b602c994cd0361d1b95bcb4047d67a31/src/rust/src/lib.rs). The current bloodhound python doesn't use those functions. So, I just disabled them with with this patch

```patch
diff --git a/Dockerfile b/Dockerfile
index 5870c77..3fcafba 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -3,6 +3,8 @@ LABEL maintainer h4rm0ny
 WORKDIR /bloodhound-data
 VOLUME /bloodhound-data

+ENV CRYPTOGRAPHY_DONT_BUILD_RUST=1
+
 COPY . /tmp/
 RUN apk update && \
     apk add --no-cache --virtual .build-deps \
```

**Comment by dirkjanm** [comment]
I've merged the PR adding the dependencies to the docker container. I personally don't really use the docker container, but I imagine cryptography will move more code towards rust in the future so having it in should keep working.
