### ISSUE TITLE
ImportError: No module named setuptools_rust

### ISSUE THREAD

**Issue by dsolstad** [fox-it/BloodHound.py#67]
I'm getting this error when doing setup.py install on a fresh Kali.

**Comment by dirkjanm** [comment]
You may need to either

* Upgrade your pip to the latest version
* `pip install cryptography==3.3.2` before installing bloodhound

**Comment by dsolstad** [comment]
That did the trick!

**Comment by dirkjanm** [comment]
closing as this is an upstream issue
