### ISSUE TITLE
Bloodhound fails to import groups.json

### ISSUE THREAD

**Issue by dsolstad** [fox-it/BloodHound.py#69]
Using the Bloodhound 4.0.2 I get the following error when importing groups.json:
"File created from incompatible collector"

users.json, computers.json and domains.json imports fine. Anyone knows what might be the problem?

**Comment by jordanbertasso** [comment]
How did you resolve this?

**Comment by barrett092** [comment]
I've been getting this consistently with the ingestor lately for groups.json

**Comment by barrett092** [comment]
I don't see any issue with the json though on my end.

**Comment by DOP7** [comment]
@dsolstad ....I am having the same error while importing users.json, computers.json and domains.json , File created from incompatible collector     erro. i am using Bloodhound 4.1.0-latest version
Can you or anyone else plz tell how didi you resolve this??

![image](https://user-images.githubusercontent.com/104196702/167286505-19ae93ee-5fd6-4520-b663-18180670eaef.png)

**Comment by dsolstad** [comment]
@DOP7 Look at the JSON and make sure it's well formatted.

**Comment by DOP7** [comment]
@dsolstad .. actually there is a issue with the current release of Blood hound....i uploaded the json files with bh earlier version and it was loaded successfully

**Comment by dsolstad** [comment]
@fr0m4bove 

Closing brackets, such as ] and }.
