### ISSUE TITLE
Feature Request - Kerberos Authentication

### ISSUE THREAD

**Issue by mubix** [fox-it/BloodHound.py#75]
Any chance kerberos auth is coming soon? ;-) pretty please...

**Comment by dirkjanm** [comment]
Any specific Kerberos auth scenario you're looking for? Or just generic support for it to avoid using NTLM?

**Comment by mubix** [comment]
Nothing specific, just looking for similar functionality to Impacket where it attempts to use the current tickets available in the KRB5CCNAME file

**Comment by glynx** [comment]
This looked so simple but was quite a struggle to get it working because the SMB requests have to performed against the hostname if kerberos is used to. And under some circumstances SMB behaves quite strange.
