### ISSUE TITLE
Won't import

### ISSUE THREAD

**Issue by 0xJs** [fox-it/BloodHound.py#81]
I installed bloodhound.py by using pip3 install bloodhound. Then I run bloodhound-python to generate a zip file. While uploading to bloodhound it won't import the files. (Stuck on Upload progress 0% for each file). Friend ran it from his Kali and I can import his zip file.

Updated every package in kali and reinstalled bloodhound and python-bloodhound. But not able to import the zip it generates. Any idea on what is causing the problem? I know you wont have much to go on, but maybe you know something.

**Comment by dirkjanm** [comment]
Can you double check which version of bloodhound-python and of the bloodhound UI you have? Both had new releases in the past day and I've only uploaded the new version to PyPi a few hours ago.

**Comment by 0xJs** [comment]
Version: 4.0.3 for bloodhound. Bloodhound-python doesn't print a version

**Comment by 0xJs** [comment]
I installed bloodhound 4.1 and it works now. Thanks!
