### ISSUE TITLE
Incorrect data format for domain trusts

### ISSUE THREAD

**Issue by itm4n** [fox-it/BloodHound.py#84]
Hello!
First of all, really nice work as usual! This tool is great.

With the recent Bloodhound update, it seems there is a problem with the JSON data formatting for domain trusts. BloodHound.py uses int values to identify trust directions and types, as show below.

```json
            "Trusts": [
                {
                    "TargetDomainName": "REDACTED_DOMAIN_NAME",
                    "TargetDomainSid": "REDACTED_DOMAIN_SID",
                    "IsTransitive": false,
                    "TrustDirection": 3,
                    "TrustType": 3,
                    "SidFilteringEnabled": true
                }
            ],
```

When importing this data in Bloodhound, the trust does not show up. So I compared this JSON output with the one produced by SharpHound and noticed this difference.

```json
            "Trusts": [
                {
                    "TargetDomainSid": "REDACTED_DOMAIN_SID",
                    "TargetDomainName": "REDACTED_DOMAIN_NAME",
                    "IsTransitive": true,
                    "SidFilteringEnabled": true,
                    "TrustDirection": "Bidirectional",
                    "TrustType": "External"
                }
            ],
```

The trust direction and type fields are string values. If I manually edit the json file produced by BloodHound.py and change these two values, the trust is properly displayed in the Bloodhound GUI.

**Comment by dirkjanm** [comment]
I've commited a fix in 2739848, would you be able to test that? Don't have any trusts in the test env here.

**Comment by itm4n** [comment]
Yes, it works! Thank you so much for the quick fix.
I tested only a "ParentChild" relation but the enumerations you added exactly reflect the ones used in the SharpHoundCommon library so I guess it should be ok with other trust types. :)

**Comment by ptr0x1** [comment]
Hey I just ran into this issue as well and was about to leave an issue. Thank you for the super quick fix and the continued work on this tool. I can also confirm the domain trust now correctly shows up both with "ParentChild" and "Forest" trusts.

**Comment by dirkjanm** [comment]
awesome 😁 will push the fixes to PyPi as well
