### ISSUE TITLE
Session enumeration through Remote Registry

### ISSUE THREAD

**Issue by itm4n** [fox-it/BloodHound.py#85]
Hi again @dirkjanm!

It's not really an issue, but it would be a really nice enhancement as it would allow a low-priv user to enumerate a lot more sessions.

Currently, there are two ways to enumerate user sessions on a remote computer:
- "session" -> RPC call to `NetrSessionEnum`
- "loggedon" -> RPC call to `NetrWkstaUserEnum`, which requires admin privs on the remote machine

The data returned by `NetrSessionEnum` is usually not that useful, and `NetrWkstaUserEnum` rarely works because of the admin privs requirement.

But... SharpHound actually implements a third technique, which is really smart and simple. It enumerates the subkeys of the `HKU` hive through the Remote Registry RPC interface. Indeed, for each locally logged on user, a key is created with the user's SID.

In such case, SharpHound generates this data:

```json
            "RegistrySessions": {
                "Results": [
                    {
                        "UserSID": "REDACTED_USER1_SID",
                        "ComputerSID": "REDACTED_COMPUTER_SID"
                    },
                    {
                        "UserSID": "REDACTED_USER2_SID",
                        "ComputerSID": "REDACTED_COMPUTER_SID"
                    }
                ],
                "Collected": true,
                "FailureReason": null
            },
```

As a low-priv user, it is usually possible to start the Remote Registry service remotely and then query the `HKU` hive.

I wrote the following test script to do this in Python with the Impacket library. You can see the original method in C# here: https://github.com/BloodHoundAD/SharpHoundCommon/blob/d8015b908773a8a6da5c9aeeb2c532a6384f49f0/src/CommonLib/Processors/ComputerSessionProcessor.cs#L208

```python
import re
from impacket.dcerpc.v5 import transport, rrp
from impacket.smbconnection import SMBConnection

TARGET_IP = "REDACTED_IP"
TARGET_NAME = "REDACTED_NAME"
USERNAME = "REDACTED_USER"
PASSWORD = "REDACTED_PASS"
DOMAIN = "REDACTED_DOMAIN"

sidRegex = "^S-1-5-21-[0-9]+-[0-9]+-[0-9]+-[0-9]+$"

# Open SMB connection and authenticate (only NTLM here)
smbConnection = SMBConnection(TARGET_NAME, TARGET_IP)
smbConnection.login(USERNAME, PASSWORD, DOMAIN, "", "")

# Start Remote Registry service
#Not implemented

# Bind to Remote Registry (over SMB)
stringBindingWinReg = r'ncacn_np:445[\pipe\winreg]'
rpc = transport.DCERPCTransportFactory(stringBindingWinReg)
rpc.set_smb_connection(smbConnection)
dce = rpc.get_dce_rpc()
dce.connect()
dce.bind(rrp.MSRPC_UUID_RRP)

# Open HKU
resp = rrp.hOpenUsers(dce)
hKey = resp['phKey']

index = 1
while True:
    try:
        resp = rrp.hBaseRegEnumKey(dce, hKey, index)
        #resp.dump()
        userSid = resp['lpNameOut'].rstrip('\0')
        res = re.match(sidRegex, userSid)
        if res:
            print(userSid)
        index += 1
    except:
        break

rrp.hBaseRegCloseKey(dce, hKey)

dce.disconnect()
smbConnection.logoff()
```

Of course, there is no error checking in this snippet. An additional step would also be required to check if the Remote Registry service is already started and try to start it if it is not. This is already implemented in the `reg.py` example script here: https://github.com/SecureAuthCorp/impacket/blob/master/examples/reg.py#L84

This method works perfectly well in my lab environment (as a low-priv user) and I'm able to get the same output data as SharpHound regarding active sessions.

**Comment by dirkjanm** [comment]
Interesting. I was not aware this worked for low-privilege users. I'll have a look at this, seems quite useful to implement.

**Comment by dirkjanm** [comment]
closing since this was merged in. thanks!
