### ISSUE TITLE
LDAP simple authentication support

### ISSUE THREAD

**Issue by awakenine** [fox-it/BloodHound.py#89]
Will you plan to support enumeration with ldap simple authentication?
ldapsearch -h
`-w passwd  bind password (for simple authentication)`

**Comment by dirkjanm** [comment]
Is there a useful scenario for this? When running from source you could easily adapt it to use SIMPLE auth instead of NTLM here: https://github.com/fox-it/BloodHound.py/blob/master/bloodhound/ad/authentication.py#L63
I don't think adding a separate parameter for this makes sense.

**Comment by dirkjanm** [comment]
I don't recall ever seeing this. If you need really need it in some cases I suggest making the small change to the source code mentioned above
