### ISSUE TITLE
BloodHound.py gets stuck in loop: "INFO: User with SID S-1-5-XXX... is logged in on DC01.example.com"

### ISSUE THREAD

**Issue by tkraus13** [fox-it/BloodHound.py#98]
This is an issue I've come across while using bloodhound-python in a couple of different domains now. It'll successfully authenticate with domain user credentials and start pulling information, but for some reason it'll get stuck in a loop and endlessly output to the screen "INFO: User with SID S-1-5-XXX... is logged in on DC01.example.com." It only does this for one user on one machine, and because the only way to end the program is ctrl-c the json files are not ended correctly and I'm unable to use the rest of the information that was successfully connected. I've tried leaving it running overnight in case it eventually ends successfully, but it just continues to run. The only way I've been able to avoid this issue is by not using the collection method "LoggedOn," which ends up not collecting a lot of valuable information. I've looked through the titles of the open and closed issues for bloodhound.py and didn't see another one like this, nor has googling brought up a similar issue. 

Has anyone else come across this issue and been able to fix it? Is it caused by an issue in bloodhound.py or by an issue/misconfiguration within the domain? If this is an issue caused by something external to bloodhound.py, a useful feature that could be added is the ability to skip collection of a particular SID or machine, through a --exclude flag or something, so in the event this happens a user could just skip the collection of that SID and still collect all the loggedon information of other users and machines. 

Additional information that may be useful: 
Full command: bloodhound-python -u username -p password -d example.com -c All,LoggedOn
I've also tried running it with "python3 bloodhound.py -u user...." and gotten the same results. 
I've also tried specifying different domain controllers (when multiple domain controllers are present) and gotten the same results.

**Comment by HydroSausager** [comment]
Same issue, +1

**Comment by dirkjanm** [comment]
thanks for the report, I've identified the issue and a fix was just pushed

**Comment by tkraus13** [comment]
Thanks for fixing it so quickly!
